insert into classes (id, grade_level, name) values (1, 4, 'Chloephaga melanoptera');
insert into classes (id, grade_level, name) values (2, 4, 'Paroaria gularis');
insert into classes (id, grade_level, name) values (3, 4, 'unavailable');
insert into classes (id, grade_level, name) values (4, 1, 'Cereopsis novaehollandiae');
insert into classes (id, grade_level, name) values (5, 5, 'Varanus komodensis');
insert into classes (id, grade_level, name) values (6, 3, null);
insert into classes (id, grade_level, name) values (7, 6, null);
insert into classes (id, grade_level, name) values (8, 8, null);
insert into classes (id, grade_level, name) values (9, 6, null);
insert into classes (id, grade_level, name) values (10, 4, 'Vulpes chama');
insert into classes (id, grade_level, name) values (11, 1, null);
insert into classes (id, grade_level, name) values (12, 3, null);
insert into classes (id, grade_level, name) values (13, 4, 'Canis aureus');
insert into classes (id, grade_level, name) values (14, 4, null);
insert into classes (id, grade_level, name) values (15, 4, 'Coendou prehensilis');
insert into classes (id, grade_level, name) values (16, 3, null);
insert into classes (id, grade_level, name) values (17, 1, null);
insert into classes (id, grade_level, name) values (18, 5, 'Mephitis mephitis');
insert into classes (id, grade_level, name) values (19, 6, 'Coluber constrictor');
insert into classes (id, grade_level, name) values (20, 2, 'Ursus arctos');
insert into classes (id, grade_level, name) values (21, 3, 'Phalacrocorax carbo');
insert into classes (id, grade_level, name) values (22, 1, null);
insert into classes (id, grade_level, name) values (23, 3, 'Rhabdomys pumilio');
insert into classes (id, grade_level, name) values (24, 1, null);
insert into classes (id, grade_level, name) values (25, 8, 'Centrocercus urophasianus');
insert into classes (id, grade_level, name) values (26, 3, 'Pseudocheirus peregrinus');
insert into classes (id, grade_level, name) values (27, 6, 'Damaliscus dorcas');
insert into classes (id, grade_level, name) values (28, 6, 'Lybius torquatus');
insert into classes (id, grade_level, name) values (29, 2, null);
insert into classes (id, grade_level, name) values (30, 3, 'Merops sp.');
insert into classes (id, grade_level, name) values (31, 0, 'Varanus salvator');
insert into classes (id, grade_level, name) values (32, 6, null);
insert into classes (id, grade_level, name) values (33, 8, null);
insert into classes (id, grade_level, name) values (34, 0, null);
insert into classes (id, grade_level, name) values (35, 4, null);
insert into classes (id, grade_level, name) values (36, 4, null);
insert into classes (id, grade_level, name) values (37, 0, 'Mirounga leonina');
insert into classes (id, grade_level, name) values (38, 6, null);
insert into classes (id, grade_level, name) values (39, 1, 'Sula dactylatra');
insert into classes (id, grade_level, name) values (40, 6, null);
insert into classes (id, grade_level, name) values (41, 5, 'Colaptes campestroides');
insert into classes (id, grade_level, name) values (42, 4, null);
insert into classes (id, grade_level, name) values (43, 8, null);
insert into classes (id, grade_level, name) values (44, 3, 'Alopochen aegyptiacus');
insert into classes (id, grade_level, name) values (45, 1, null);
insert into classes (id, grade_level, name) values (46, 3, 'Funambulus pennati');
insert into classes (id, grade_level, name) values (47, 4, null);
insert into classes (id, grade_level, name) values (48, 5, null);
insert into classes (id, grade_level, name) values (49, 7, 'Felis yagouaroundi');
insert into classes (id, grade_level, name) values (50, 4, 'Pelecans onocratalus');
insert into classes (id, grade_level, name) values (51, 5, 'Centrocercus urophasianus');
insert into classes (id, grade_level, name) values (52, 5, 'Priodontes maximus');
insert into classes (id, grade_level, name) values (53, 1, 'Castor fiber');
insert into classes (id, grade_level, name) values (54, 1, null);
insert into classes (id, grade_level, name) values (55, 6, 'Spheniscus magellanicus');
insert into classes (id, grade_level, name) values (56, 6, 'Chelodina longicollis');
insert into classes (id, grade_level, name) values (57, 4, 'Pseudocheirus peregrinus');
insert into classes (id, grade_level, name) values (58, 5, null);
insert into classes (id, grade_level, name) values (59, 5, 'Mungos mungo');
insert into classes (id, grade_level, name) values (60, 0, 'Rhea americana');
insert into classes (id, grade_level, name) values (61, 7, null);
insert into classes (id, grade_level, name) values (62, 0, 'Tursiops truncatus');
insert into classes (id, grade_level, name) values (63, 7, 'Threskionis aethiopicus');
insert into classes (id, grade_level, name) values (64, 3, null);
insert into classes (id, grade_level, name) values (65, 7, 'Laniaurius atrococcineus');
insert into classes (id, grade_level, name) values (66, 4, 'Fratercula corniculata');
insert into classes (id, grade_level, name) values (67, 2, 'Canis aureus');
insert into classes (id, grade_level, name) values (68, 1, null);
insert into classes (id, grade_level, name) values (69, 4, 'Francolinus coqui');
insert into classes (id, grade_level, name) values (70, 2, 'Pseudocheirus peregrinus');
insert into classes (id, grade_level, name) values (71, 6, null);
insert into classes (id, grade_level, name) values (72, 3, null);
insert into classes (id, grade_level, name) values (73, 2, null);
insert into classes (id, grade_level, name) values (74, 5, 'Larus dominicanus');
insert into classes (id, grade_level, name) values (75, 7, 'Castor fiber');
insert into classes (id, grade_level, name) values (76, 4, null);
insert into classes (id, grade_level, name) values (77, 3, 'Trichoglossus chlorolepidotus');
insert into classes (id, grade_level, name) values (78, 4, null);
insert into classes (id, grade_level, name) values (79, 1, null);
insert into classes (id, grade_level, name) values (80, 5, null);
insert into classes (id, grade_level, name) values (81, 6, null);
insert into classes (id, grade_level, name) values (82, 4, 'Cabassous sp.');
insert into classes (id, grade_level, name) values (83, 5, null);
insert into classes (id, grade_level, name) values (84, 0, null);
insert into classes (id, grade_level, name) values (85, 6, null);
insert into classes (id, grade_level, name) values (86, 3, null);
insert into classes (id, grade_level, name) values (87, 3, 'Myiarchus tuberculifer');
insert into classes (id, grade_level, name) values (88, 5, null);
insert into classes (id, grade_level, name) values (89, 2, 'Tauraco porphyrelophus');
insert into classes (id, grade_level, name) values (90, 7, null);
insert into classes (id, grade_level, name) values (91, 8, 'Sauromalus obesus');
insert into classes (id, grade_level, name) values (92, 6, null);
insert into classes (id, grade_level, name) values (93, 3, 'Crotalus adamanteus');
insert into classes (id, grade_level, name) values (94, 8, 'Dendrocitta vagabunda');
insert into classes (id, grade_level, name) values (95, 6, 'Trichoglossus haematodus moluccanus');
insert into classes (id, grade_level, name) values (96, 8, 'Phalaropus lobatus');
insert into classes (id, grade_level, name) values (97, 1, null);
insert into classes (id, grade_level, name) values (98, 7, 'Pteronura brasiliensis');
insert into classes (id, grade_level, name) values (99, 3, 'Lemur fulvus');
insert into classes (id, grade_level, name) values (100, 0, null);
